import { createContext } from 'react';

import { Config, AppStateContextProps } from './types';

const initialState: AppStateContextProps = {
	update: null,
	playText: '',
	publicIp: '',
	profiles: [],
	shareCode: '',
	modpackId: '',
	appVersion: '',
	statusText: '',
	hostPort: 7878,
	syncProgress: 0,
	hostAddress: '',
	modpackName: '',
	tmmProfiles: [],
	isHosting: false,
	isReadOnly: false,
	isInstalled: false,
	needsUpdate: false,
	playDisabled: false,
	activeProfile: null,
	config: {} as Config,
	activeGame: 'valheim',
	setHostPort: () => {},
	activeProfileId: null,
	isShareStarting: false,
	setIsHosting: () => {},
	setShareCode: () => {},
	setModpackId: () => {},
	activeTmmProfile: null,
	progressType: undefined,
	setSyncStatus: () => {},
	setActiveGame: () => {},
	setHostAddress: () => {},
	setModpackName: () => {},
	setConfig: async () => {},
	syncStatus: 'NotConnected',
	setIsShareStarting: () => {},
	deleteProfile: async () => {},
	refreshProfiles: async () => {},
	setActiveProfile: async () => {},
	refreshTmmProfiles: async () => {},
	setActiveTmmProfile: async () => {},
	createProfile: async () => ({ id: '', name: '', path: '', mods: [], gameId: '', createdAt: 0, updatedAt: 0 })
};

export const AppStateContext = createContext<AppStateContextProps>(initialState);
